### ISSUE TITLE
Back Office Css bug for Fontawesome 5

### ISSUE THREAD

**Issue by cyrilwseils** [DirkPersky/typo3-rte-ckeditor-fontawesome#17] opened 2021-03-03 14:48 UTC
Hi 

I have a problem with back-office css when i use the extenson with fontawesome 5.
If i open the pop up with fontawesome icon in RTE, the css will change (cf picture)
![bugCss](https://user-images.githubusercontent.com/30345339/109821070-e3175480-7c35-11eb-866c-524146ab707b.PNG).

If i test with : RTE.default.preset = fullFA4 or RTE.default.preset = defaultFA4 i don't have the problem. But with RTE.default.preset = full or default i have. 

I'm on TYPO3 9.5.24 and tested the extension on : 10.1.0 and 9.5.2.

An other problem is my configuration file works for fontawesome pro on the 9.5.2 version but not on the 10.1.0. I only have free icons when i'm on the last version on extension but works perfectly for 9.5.2

Thanks !

**Comment by DirkPersky** [comment] 2021-03-03 15:41
Hey thanks for reporting, i will take a look in the next week to it.
I hope i can reproduce your issue.

**Comment by DirkPersky** [comment] 2021-03-11 17:14
He,

im sorry, but i cant reproduce your issue.
![image](https://user-images.githubusercontent.com/1736266/110826243-29ebf680-8295-11eb-84c2-672baf0553ab.png)

- TYPO3 9.5.24 
- PlugIn Version 10.1.0

If you can give me access to your system i maybe can find the issue for that.

Greetings
Dirk

**Comment by DirkPersky** [comment] 2021-03-11 20:51
I have refactored the complete code, i hope that fixes your issue.

**Comment by linawolf** [comment] 2021-10-19 08:14
We have the same problem with TYPO3 11.5.1  and 
rte_ckeditor_fontawesome | 10.3.1

It seems like the css that is normally applied only to the RTE content gets applied to the complete backend frame. This includes fonts and fontsizes, buttons etc:

Before inserting icon
![Screen1](https://user-images.githubusercontent.com/48202465/137870074-36c0122f-4091-4998-855b-de78871faa14.png)

Right after inserting icon
![Screen2](https://user-images.githubusercontent.com/48202465/137870080-834bee86-66e8-455a-964d-3a74e8d941cd.png)

**Comment by olegkarun** [comment] 2022-03-15 10:10
The same problem - if there are any custom styles included RTE all of them committed to whole backend when FontAwesome modal open 
"dirkpersky/typo3-rte-ckeditor-fontawesome": "^11.5",
"typo3/cms-backend": "^11.5.0",

**Comment by DirkPersky** [comment] 2022-03-15 13:38
shoud be gone in latest release 1.5.3

**Comment by Tim-Obert** [comment] 2022-03-15 14:47
First of all thank you. Sadly I have to tell you that the new version doesn't fix the Issue. 
I'm using FontAwesome Pro and with the new version the Css won't get loaded so the Icons can't be displayed right (as shown in the image).
![image](https://user-images.githubusercontent.com/45205076/158404188-b988fd7e-1909-4334-ac11-b0667b90ac20.png)

**Comment by DirkPersky** [comment] 2022-03-15 17:35
Hmm becouse i dont have FA Pro:
Is there a default CDN were you load it from?
Had u added it localy?
Is there a default name of the file?

**Comment by Tim-Obert** [comment] 2022-03-17 09:42
Yes I added the file locally. The file is build from scss to css and contains all styles of the rte. But in my case it would also be possible to split this into RTE Styles and only Font-Awesome with a specific name. 
I think the name of the file of Font-Awesome pro is named as same as the other versions "all.css".

**Comment by DirkPersky** [comment] 2022-03-19 10:07
okay, found a solution.
The yml config will change with next release.

```yml
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Full.yaml" }
  - { resource: "EXT:rte_ckeditor_fontawesome/Configuration/RTE/PluginFA5Pro.yaml" }
# Add configuration for the editor
editor:
  config:
    fontAwesome:
      - "LINK TO FONTAWESOME PRO"
```

**Closed** 2022-03-19 10:20 UTC
Labels: bug

**Comment by Patta** [comment] 2022-03-22 10:29
The fontawesome css file is now added twice, with `loadCSS` in the document which i don't think is necessary and in the rte frame with `addContentsCss`.
